sleepConfigs:
   dummy-config:
     enabled: false
     timeZone: "Europe/Rome" # this is also the default, if not specified
     weekdays: "1-5"
     sleepAt: "16:30"
     duration: 10h
     namespaces:
     - a
     - b
     - c